language: python
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.8-dev"
    - python: "3.9-dev"
    - python: "pypy3"
  allow_failures:
    - python: "3.8-dev"
    - python: "3.9-dev"
    - python: "pypy3"
install:
  - pip3 install .
before_script:
  - pip3 install coverage
  - pip3 install coveralls
script:
  - coverage run --source mavehgvs -m unittest
after_success:
  - coveralls
